### ISSUE TITLE
Errors when playing non-jellyfin content

### ISSUE THREAD

**Issue by ltGuillaume** [jellyfin/jellycon#114]
**Describe the bug**

I'm often getting the following error in my logs:
```
 INFO <general>: Creating InputStream
 INFO <general>: AddOnLog: inputstream.adaptive: SetVideoResolution (1920 x 1080)

ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                 Error Type: <class 'json.decoder.JSONDecodeError'>
                 Error Contents: Expecting value: line 1 column 1 (char 0)
                 Traceback (most recent call last):
                   File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.jellycon\resources\lib\play_utils.py", line 1134, in onPlayBackStarted
                     play_data = get_playing_data()
                   File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.jellycon\resources\lib\play_utils.py", line 1077, in get_playing_data
                     play_data = json.loads(play_data_string)
                   File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\__init__.py", line 357, in loads
                     return _default_decoder.decode(s)
                   File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\decoder.py", line 337, in decode
                     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\decoder.py", line 355, in raw_decode
                     raise JSONDecodeError("Expecting value", s, err.value) from None
                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                   -->End of Python script error report<--

 INFO <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file.
```

or

```
   INFO <general>: CPythonInvoker(5, D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.netflix\addon.py): script successfully run
   INFO <general>: VideoPlayer::OpenFile: plugin://plugin.video.netflix/play/show/?/season/?/episode/?/?profile_guid=???
   INFO <general>: Creating InputStream
   INFO <general>: AddOnLog: inputstream.adaptive: SetVideoResolution (1920 x 1080)
  ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                   Error Type: <class 'json.decoder.JSONDecodeError'>
                   Error Contents: Expecting value: line 1 column 1 (char 0)
                   Traceback (most recent call last):
                     File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.jellycon\resources\lib\play_utils.py", line 1134, in onPlayBackStarted
                       play_data = get_playing_data()
                     File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.jellycon\resources\lib\play_utils.py", line 1077, in get_playing_data
                       play_data = json.loads(play_data_string)
                     File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\__init__.py", line 357, in loads
                       return _default_decoder.decode(s)
                     File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\decoder.py", line 337, in decode
                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                     File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\decoder.py", line 355, in raw_decode
                       raise JSONDecodeError("Expecting value", s, err.value) from None
                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                   -->End of Python script error report<--
                   
   INFO <general>: JELLYFIN.service -> ERROR::service.py:182 Exception in Playback Monitor: Expecting value: line 1 column 1 (char 0)
   INFO <general>: JELLYFIN.service -> ERROR::service.py:183 Traceback (most recent call last):
                     File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.jellycon\service.py", line 127, in <module>
                       send_progress()
                     File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.jellycon\resources\lib\play_utils.py", line 880, in send_progress
                       play_data = get_playing_data()
                     File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.jellycon\resources\lib\play_utils.py", line 1077, in get_playing_data
                       play_data = json.loads(play_data_string)
                     File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\__init__.py", line 357, in loads
                       return _default_decoder.decode(s)
                     File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\decoder.py", line 337, in decode
                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                     File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\decoder.py", line 355, in raw_decode
                       raise JSONDecodeError("Expecting value", s, err.value) from None
                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                   
INFO <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file.
```

Since I am in fact having memory leak issues with the kodi.exe process, I thought I'd address this.

As you can see, this is playback of a _Netflix_ video, and somehow JellyCon thinks it should do something with it, and fails as well.

First of all, I don't understand why JellyCon still has some hook for any playback; why doesn't it just stick to only processing its own videos? Second, apparently it fails with an exception when it can't find playing data.

**To Reproduce**

1. Just open Kodi and start a Netflix video

**System (please complete the following information):**
 - OS: Windows
 - Jellyfin Version: 10.7.7
 - Kodi Version: 19.3
 - Addon Version: v0.4.7+py3

**Comment by mcarlton00** [comment]
Kodi doesn't differentiate between video sources.  So we have to hook into everything and then determine if we should be doing something with it.  I think I had fixed this before, but judging by the traceback, it seems I may have broke it again while fixing #69

**Comment by ltGuillaume** [comment]
Aaah yes, I'm sorry, now I remember you mentioning this before. But yeah, the log entries seem to be back in the latest release.
