### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by yed01** [jellyfin/jellycon#121]
When I restart Kodi I get following error message and I can't access the files on the Jellyfin-server. If I disable and re-enable the addon it works again as expected.
This happens every time I restart Kodi. 
Tested Release 0.4.7 and 0.4.5, both with this error.
Kodi 19 on CoreELEC

2022-02-03 11:27:06.613 T:4207     INFO <general>: JELLYFIN.service -> ERROR::service.py:182 Exception in Playback Monitor: 'NoneType' object i>
2022-02-03 11:27:06.615 T:4207     INFO <general>: JELLYFIN.service -> ERROR::service.py:183 Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.jellycon/service.py", line 163, in <module>
                                                       set_library_window_values(user_changed)
                                                     File "/storage/.kodi/addons/plugin.video.jellycon/resources/lib/menu_functions.py", line 1>
                                                       for item in result:
                                                   TypeError: 'NoneType' object is not iterable

**Comment by mcarlton00** [comment]
I'm not sure what it's trying to change there.  It seems to think that the user has changed and it needs to update values, but then isn't receiving any data back from the server to update.

It seems as though this should be an easy fix if you want to test it since I haven't been able to replicate this.  Change line 1117 of `/storage/.kodi/addons/plugin.video.jellycon/resources/lib/menu_functions.py` from

```python
result = result.get("Items")
```
to
```python
result = result.get("Items", [])
```

**Comment by yed01** [comment]
Seems to work.
Thank you.

**Comment by mcarlton00** [comment]
We'll leave it open for now as a reminder to fix the issue in the repo
