### ISSUE TITLE
Connection Error: Strings must be encoded

### ISSUE THREAD

**Issue by zealucard** [jellyfin/jellycon#125]
When selecting a movie or a collection/boxset, a notification error is displayed, and nothing happen exception a notification error: 

> Connection Error: Strings must be encoded before hashing.

**To Reproduce**
1. Go to Movies
2. Click on a movie or a collection containing french charatcter (é, è, ê, ô, ç, etc.)
3. See error: Strings must be encoded before hashing.

**Expected behavior**
Be able to navigate into collection and to play movies using french characters into their title.

**Logs**
`2022-02-28 11:11:36.605 T:14336    INFO <general>: JELLYFIN.resources.lib.functions -> DEBUG::resources/lib/functions.py:179 ===== JellyCon FINISHED =====
2022-02-28 11:11:36.605 T:14336    INFO <general>: JELLYFIN.resources.lib.tracking -> INFO::resources/lib/tracking.py:31 timing_data|main_entry_point|1646043096.566709|1646043096.6059206|?media_type=BoxSet&mode=GET_CONTENT&url=%7bserver%7d%2fUsers%2f%7buserid%7d%2fitems%3fParentId%3dd005cefbaa36c0e7717c2975cc979075%26IsVirtualUnAired%3dfalse%26IsMissing%3dfalse%26Fields%3d%7bfield_filters%7d%26format%3djson
2022-02-28 11:11:36.606 T:14336    INFO <general>: CPythonInvoker(13, /home/zealucard/.kodi/addons/plugin.video.jellycon/default.py): script successfully run
2022-02-28 11:11:36.606 T:14336    INFO <general>: CPythonInvoker(13, /home/zealucard/.kodi/addons/plugin.video.jellycon/default.py): waiting on thread 140601176766016
2022-02-28 11:11:36.617 T:14337    INFO <general>: JELLYFIN.resources.lib.downloadutils -> **ERROR::resources/lib/downloadutils.py:719 Traceback (most recent call last):
                                                     File "/home/zealucard/.kodi/addons/plugin.video.jellycon/resources/lib/downloadutils.py", line 702, in download_url
                                                       m.update(username)
                                                   TypeError: Strings must be encoded before hashing**
                                                   
2022-02-28 11:11:36.617 T:14337    INFO <general>: JELLYFIN.resources.lib.downloadutils -> ERROR::resources/lib/downloadutils.py:720 Unable to connect to {jellyfin-server} : Strings must be encoded before hashing
2022-02-28 11:11:36.618 T:14337    INFO <general>: JELLYFIN.resources.lib.tracking -> INFO::resources/lib/tracking.py:31 timing_data|download_url|1646043096.5983245|1646043096.6181026|{server}/Users/{userid}/items?ParentId=d005cefbaa36c0e7717c2975cc979075&IsVirtualUnAired=false&IsMissing=false&Fields={field_filters}&format=json`

**Screenshots**

**System (please complete the following information):**
 - OS: Linux (EndeavourOS - Kernel 5.16.11 - Plasma 5.24.2 - python 3.10.2)
 - Jellyfin Version: 10.8.0
 - Kodi Version: 19.3
 - Addon Version: 0.4.7+py3

**Comment by zealucard** [comment]
> When selecting a movie or a collection/boxset, a notification error is displayed, and nothing happen exception a notification error:
> 
> > Connection Error: Strings must be encoded before hashing.
> 
> **To Reproduce**
> 
> 1. Go to Movies
> 2. Click on a movie or a collection containing french charatcter (é, è, ê, ô, ç, etc.)
> 3. See error: Strings must be encoded before hashing.
> 
> **Expected behavior** Be able to navigate into collection and to play movies using french characters into their title.
> 
> **Logs** `2022-02-28 11:11:36.605 T:14336 INFO : JELLYFIN.resources.lib.functions -> DEBUG::resources/lib/functions.py:179 ===== JellyCon FINISHED ===== 2022-02-28 11:11:36.605 T:14336 INFO : JELLYFIN.resources.lib.tracking -> INFO::resources/lib/tracking.py:31 timing_data|main_entry_point|1646043096.566709|1646043096.6059206|?media_type=BoxSet&mode=GET_CONTENT&url=%7bserver%7d%2fUsers%2f%7buserid%7d%2fitems%3fParentId%3dd005cefbaa36c0e7717c2975cc979075%26IsVirtualUnAired%3dfalse%26IsMissing%3dfalse%26Fields%3d%7bfield_filters%7d%26format%3djson 2022-02-28 11:11:36.606 T:14336 INFO : CPythonInvoker(13, /home/zealucard/.kodi/addons/plugin.video.jellycon/default.py): script successfully run 2022-02-28 11:11:36.606 T:14336 INFO : CPythonInvoker(13, /home/zealucard/.kodi/addons/plugin.video.jellycon/default.py): waiting on thread 140601176766016 2022-02-28 11:11:36.617 T:14337 INFO : JELLYFIN.resources.lib.downloadutils -> **ERROR::resources/lib/downloadutils.py:719 Traceback (most recent call last): File "/home/zealucard/.kodi/addons/plugin.video.jellycon/resources/lib/downloadutils.py", line 702, in download_url m.update(username) TypeError: Strings must be encoded before hashing**
> 
> 2022-02-28 11:11:36.617 T:14337 INFO : JELLYFIN.resources.lib.downloadutils -> ERROR::resources/lib/downloadutils.py:720 Unable to connect to {jellyfin-server} : Strings must be encoded before hashing 2022-02-28 11:11:36.618 T:14337 INFO : JELLYFIN.resources.lib.tracking -> INFO::resources/lib/tracking.py:31 timing_data|download_url|1646043096.5983245|1646043096.6181026|{server}/Users/{userid}/items?ParentId=d005cefbaa36c0e7717c2975cc979075&IsVirtualUnAired=false&IsMissing=false&Fields={field_filters}&format=json`
> 
> **Screenshots**
> 
> **System (please complete the following information):**
> 
> * OS: Linux (EndeavourOS - Kernel 5.16.11 - Plasma 5.24.2 - python 3.10.2)
> * Jellyfin Version: 10.8.0
> * Kodi Version: 19.3
> * Addon Version: 0.4.7+py3

**Comment by zealucard** [comment]
I didn't really understand what happened. So, the issue is not because of french characters in title, but because the error message was not correctly encoded.
I modified line 702 into resources/lib/downloadutils.py from '_m.update(username)_' to '_m.update(username.encode(encoding = 'UTF-8', errors = 'strict'))_', and the error message was clear to me.
