### ISSUE TITLE
Cannot connect to server with version 0.5.0+py2 on Kodi 18.7

### ISSUE THREAD

**Issue by efelon** [jellyfin/jellycon#171]
**Describe the bug**
Immediately after upgrade to 0.5.0+py2 on Kodi 18.7, I see a message about an error occurred and I should check the logs (see below). 

**To Reproduce**
1. Update to the described version
2. Try to access any menu from jellycon

**Expected behavior**
Working after update

**Logs**
Jellyfin logs:
```
[WRN] WS 192.168.23.30 error receiving data: The remote party closed the WebSocket connection without completing the close handshake.
```
Kodi logs:
A few of:
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: Required argument 'tz' (pos 1) not found
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.jellycon/default.py", line 18, in <module>
                                                main_entry_point()
                                              File "/home/kodi/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 23, in wrapper
                                                value = func(*args, **kwargs)
                                              File "/home/kodi/.kodi/addons/plugin.video.jellycon/resources/lib/functions.py", line 78, in main_entry_point
                                                check_server(change_user=True, notify=False)
                                              File "/home/kodi/.kodi/addons/plugin.video.jellycon/resources/lib/server_detect.py", line 221, in check_server
                                                users, user_selection = user_select(api, current_username)
                                              File "/home/kodi/.kodi/addons/plugin.video.jellycon/resources/lib/server_detect.py", line 333, in user_select
                                                user_item = create_user_listitem(api.server, user)
                                              File "/home/kodi/.kodi/addons/plugin.video.jellycon/resources/lib/server_detect.py", line 378, in create_user_listitem
                                                ago = datetime.now().astimezone() - last_active_date
                                            TypeError: Required argument 'tz' (pos 1) not found
                                            -->End of Python script error report<--
```
and more of:
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: coercing to Unicode: need string or buffer, NoneType found
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.jellycon/default.py", line 18, in <module>
                                                main_entry_point()
                                              File "/home/kodi/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 23, in wrapper
                                                value = func(*args, **kwargs)
                                              File "/home/kodi/.kodi/addons/plugin.video.jellycon/resources/lib/functions.py", line 144, in main_entry_point
                                                get_content(param_url, params)
                                              File "/home/kodi/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 23, in wrapper
                                                value = func(*args, **kwargs)
                                              File "/home/kodi/.kodi/addons/plugin.video.jellycon/resources/lib/dir_functions.py", line 108, in get_content
                                                dir_items, detected_type, total_records = process_directory(url, progress, params, use_cache)
                                              File "/home/kodi/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 23, in wrapper
                                                value = func(*args, **kwargs)
                                              File "/home/kodi/.kodi/addons/plugin.video.jellycon/resources/lib/dir_functions.py", line 247, in process_directory
                                                url = url.replace('{userid}', user_id)
                                            TypeError: coercing to Unicode: need string or buffer, NoneType found
                                            -->End of Python script error report<--
```

**System (please complete the following information):**
 - OS: Debian (Raspberry Pi OS)
 - Jellyfin Version: `Jellyfin.Server 10.8.0.0 (Linux  5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux)`
 - Kodi Version: `18.7`
 - Addon Version: 0.5.0+py2

**Additional context**
I tried without success:
* deinstall and install
* reselect server
* reselect user

I had to go back to version 0.4.7+py2.

**Comment by mcarlton00** [comment]
It's been a few days since release and I was just starting to think that maybe I'd done a release without any new bugs.  So thanks for bursting my bubble. :laughing: 

The `tz` error looks like a python 2 exclusive thing.  I'll need to find a way to either compile v18 or go through a VM to get to an older version of Kodi and investigate this.  I suspect the other error is a side effect of the install wizard failing.

**Comment by efelon** [comment]
> It's been a few days since release and I was just starting to

I feel you, and I'm a little bit sorry for being the one who bursted.

Let me add some more information just in case:
```
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

# python --version
Python 2.7.16
```
This is my "mediapi" which I could not yet setup up satisfactory on bullseye with Kodi19. I hope that this is not some breaking, support for python2 dropping thingy.

**Comment by mcarlton00** [comment]
Nothing so drastic as that, as much as I'd like to.  Dates in python are just notoriously obnoxious, and what I wrote apparently relied on py3 defaults.  Absolute worst case scenario I just rip out the date comparison bits from menus, but I think I should have a proper solution in a little while.
