### ISSUE TITLE
Cannot connect to Swizzin created Jellyfin server on LAN due to self-signed certificate.

### ISSUE THREAD

**Issue by IModThings** [jellyfin/jellycon#185]
On Fedora Linux. Jellycon 0.5.2

Unsure if this is expected behavior. Please close if this is intended.

Error bellow. 

`2022-07-18 22:37:59.892 T:823735   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.SSLError'>
                                                   Error Contents: HTTPSConnectionPool(host='10.42.0.102', port=443): Max retries exceeded with url: /System/Info/Public (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))
                                                   Traceback (most recent call last):
                                                     File "/home/alexander/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 703, in urlopen
                                                       httplib_response = self._make_request(
                                                     File "/home/alexander/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 386, in _make_request
                                                       self._validate_conn(conn)
                                                     File "/home/alexander/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 1040, in _validate_conn
                                                       conn.connect()
                                                     File "/home/alexander/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 414, in connect
                                                       self.sock = ssl_wrap_socket(
                                                     File "/home/alexander/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py", line 453, in ssl_wrap_socket
                                                       ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
                                                     File "/home/alexander/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py", line 495, in _ssl_wrap_socket_impl
                                                       return ssl_context.wrap_socket(sock)
                                                     File "/usr/lib64/python3.10/ssl.py", line 513, in wrap_socket
                                                       return self.sslsocket_class._create(
                                                     File "/usr/lib64/python3.10/ssl.py", line 1071, in _create
                                                       self.do_handshake()
                                                     File "/usr/lib64/python3.10/ssl.py", line 1342, in do_handshake
                                                       self._sslobj.do_handshake()
                                                   ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/alexander/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 440, in send
                                                       resp = conn.urlopen(
                                                     File "/home/alexander/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 785, in urlopen
                                                       retries = retries.increment(
                                                     File "/home/alexander/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 592, in increment
                                                       raise MaxRetryError(_pool, url, error or ResponseError(cause))
                                                   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.42.0.102', port=443): Max retries exceeded with url: /System/Info/Public (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/alexander/.kodi/addons/plugin.video.jellycon/default.py", line 18, in <module>
                                                       main_entry_point()
                                                     File "/home/alexander/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 23, in wrapper
                                                       value = func(*args, **kwargs)
                                                     File "/home/alexander/.kodi/addons/plugin.video.jellycon/resources/lib/functions.py", line 148, in main_entry_point
                                                       check_server()
                                                     File "/home/alexander/.kodi/addons/plugin.video.jellycon/resources/lib/server_detect.py", line 184, in check_server
                                                       result = api.get('/System/Info/Public')
                                                     File "/home/alexander/.kodi/addons/plugin.video.jellycon/resources/lib/jellyfin.py", line 37, in get
                                                       r = requests.get(url, headers=self.headers, verify=self.verify_cert)
                                                     File "/home/alexander/.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
                                                       return request('get', url, params=params, **kwargs)
                                                     File "/home/alexander/.kodi/addons/script.module.requests/lib/requests/api.py", line 61, in request
                                                       return session.request(method=method, url=url, **kwargs)
                                                     File "/home/alexander/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 529, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                     File "/home/alexander/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 667, in send
                                                       history = [resp for resp in gen]
                                                     File "/home/alexander/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 667, in <listcomp>
                                                       history = [resp for resp in gen]
                                                     File "/home/alexander/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 237, in resolve_redirects
                                                       resp = self.send(
                                                     File "/home/alexander/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 645, in send
                                                       r = adapter.send(request, **kwargs)
                                                     File "/home/alexander/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 517, in send
                                                       raise SSLError(e, request=request)
                                                   requests.exceptions.SSLError: HTTPSConnectionPool(host='10.42.0.102', port=443): Max retries exceeded with url: /System/Info/Public (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))
                                                   -->End of Python script error report<--`

**Comment by mcarlton00** [comment]
It is intended, but you can disable it.  Add-ons -> Video add-ons -> JellyCon -> Add-on Actions -> Show add-on settings.  From here you can toggle if you want to verify https certificates.

**Comment by IModThings** [comment]
Ah thanks. That worked perfectly.
