### ISSUE TITLE
Error on playback with 5.3

### ISSUE THREAD

**Issue by caiusseverus** [jellyfin/jellycon#188]
**Describe the bug**
Unable to play any media using jellycon on libreelec. The error message says to check logs.

**To Reproduce**

Attempt to play any video.

**Expected behavior**
Video should play.

**Logs**
```
2022-07-20 03:58:37.537 T:1165     INFO <general>: JELLYFIN.resources.lib.functions -> INFO::resources/lib/functions.py:847 Sending jellycon_play_action : {'action': 'play', 'item_id': '5f5ef4d68fd3d3dc8b75dc6878d20413', 'auto_resume': '-1', 'force_transcode': False, 'media_source_id': '', 'subtitle_stream_index': None, 'audio_stream_index': None}
2022-07-20 03:58:37.610 T:1165     INFO <general>: JELLYFIN.resources.lib.play_utils -> INFO::resources/lib/play_utils.py:385 Play URL: {jellyfin-server}/Videos/5f5ef4d68fd3d3dc8b75dc6878d20413/stream?static=True&PlaySessionId=6b8ad2f3defe4e34ac984d0f76100d33&MediaSourceId=5f5ef4d68fd3d3dc8b75dc6878d20413 Playback Type: 1 ListItem Properties: []
2022-07-20 03:58:37.651 T:1165    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: '>' not supported between instances of 'str' and 'int'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.jellycon/default.py", line 18, in <module>
                                                       main_entry_point()
                                                     File "/storage/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 23, in wrapper
                                                       value = func(*args, **kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.jellycon/resources/lib/functions.py", line 146, in main_entry_point
                                                       play_action(params)
                                                     File "/storage/.kodi/addons/plugin.video.jellycon/resources/lib/functions.py", line 848, in play_action
                                                       play_file(play_info)
                                                     File "/storage/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 23, in wrapper
                                                       value = func(*args, **kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.jellycon/resources/lib/play_utils.py", line 461, in play_file
                                                       if sys.argv[1] > 1:
                                                   TypeError: '>' not supported between instances of 'str' and 'int'
                                                   -->End of Python script error report<--
```

**System (please complete the following information):**
 - OS: Libreelec 10.0.2
 - Jellyfin Version: 10.8
 - Kodi Version: 19.4
 - Addon Version: 5.3

**Additional context**
Reverting to 5.2 works as expected.

**Comment by mcarlton00** [comment]
0.5.4 has been released and should fix this.  Sorry about that.

**Comment by caiusseverus** [comment]
Thanks for the quick update. All working OK now.
