### ISSUE TITLE
More bugs with fast user switching

### ISSUE THREAD

**Issue by cmsimike** [jellyfin/jellycon#207]
**Describe the bug**
Currently saving users and trying to switch users still seems broken for me. 

**To Reproduce**

1. Login as userA with no password
2. Verify libraries load
4. Login as userB with a password
5. See error

**Expected behavior**
I should be able to switch users and see their libraries without deleting `auth.json`

**Logs**
```
2022-08-17 18:03:09.896 T:1786448   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.jellycon/?mode=SHOW_ADDON_MENU&type=library
2022-08-17 18:03:09.902 T:1626882   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.jellycon/?mode=SHOW_ADDON_MENU&type=library) failed
```

```
2-08-17 18:04:49.610 T:1787296   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: replace() argument 2 must be str, not None
                                                   Traceback (most recent call last):
                                                     File "/home/mike/.kodi/addons/plugin.video.jellycon/default.py", line 18, in <module>
                                                       main_entry_point()
                                                     File "/home/mike/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 23, in wrapper
                                                       value = func(*args, **kwargs)
                                                     File "/home/mike/.kodi/addons/plugin.video.jellycon/resources/lib/functions.py", line 144, in main_entry_point
                                                       get_content(param_url, params)
                                                     File "/home/mike/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 23, in wrapper
                                                       value = func(*args, **kwargs)
                                                     File "/home/mike/.kodi/addons/plugin.video.jellycon/resources/lib/dir_functions.py", line 108, in get_content
                                                       dir_items, detected_type, total_records = process_directory(url, progress, params, use_cache)
                                                     File "/home/mike/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 23, in wrapper
                                                       value = func(*args, **kwargs)
                                                     File "/home/mike/.kodi/addons/plugin.video.jellycon/resources/lib/dir_functions.py", line 247, in process_directory
                                                       url = url.replace('{userid}', user_id)
                                                   TypeError: replace() argument 2 must be str, not None
                                                   -->End of Python script error report<--
```

**Screenshots**

**System (please complete the following information):**
 - OS: Ubuntu 21.10
 - Jellyfin Version: 10.8.1
 - Kodi Version: 19.4
 - Addon Version: .5.5

**Additional context**
This very much feels like the previous issues I've opened. It seemed to be working for a while but back to where we were before.
https://github.com/jellyfin/jellycon/issues/192

Additionally, maybe this isn't a bug (but feels like it to me) when you have fast user switching on, and the menu pops up asking me to log in, I *feel like* the previously logged in users should be there but I've never seen it.

**Comment by mcarlton00** [comment]
It looks like the last release didn't go through all the way like I thought it did.  This should be fixed in version 0.5.6 that was just added to the addon repo today.

> Additionally, maybe this isn't a bug (but feels like it to me) when you have fast user switching on, and the menu pops up asking me to log in, I feel like the previously logged in users should be there but I've never seen it.

It pulls the displayed user list from the server api endpoint.  So if you're users are hidden from the login screen, that makes sense.  However, it does probably make sense to also query the local saved users list and add them to the list

**Comment by cmsimike** [comment]
Thank you for the heads up!

**Comment by cmsimike** [comment]
Confirmed - looked better now that I'm on .56. Thanks!
