### ISSUE TITLE
Can't load remote library

### ISSUE THREAD

**Issue by taiyoko** [jellyfin/jellycon#230]
**Describe the bug**
Attempting to view media from remote Jellyfin library gives a generic "see logs" error.

**To Reproduce**

1. Go to Addons
2. Go to JellyCon
3. Go to Global Lists
4. Go to Movies
5. Go to Movies - Show All

**Expected behavior**
List of movies available on the server to populate

**Logs**
`2022-10-07 18:35:44.012 T:9402    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: replace() argument 2 must be str, not None
                                                   Traceback (most recent call last):
                                                     File "/home/NerdTV/.kodi/addons/plugin.video.jellycon/default.py", line 18, in <module>
                                                       main_entry_point()
                                                     File "/home/NerdTV/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 23, in wrapper
                                                       value = func(*args, **kwargs)
                                                     File "/home/NerdTV/.kodi/addons/plugin.video.jellycon/resources/lib/functions.py", line 144, in main_entry_point
                                                       get_content(param_url, params)
                                                     File "/home/NerdTV/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 23, in wrapper
                                                       value = func(*args, **kwargs)
                                                     File "/home/NerdTV/.kodi/addons/plugin.video.jellycon/resources/lib/dir_functions.py", line 108, in get_content
                                                       dir_items, detected_type, total_records = process_directory(url, progress, params, use_cache)
                                                     File "/home/NerdTV/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 23, in wrapper
                                                       value = func(*args, **kwargs)
                                                     File "/home/NerdTV/.kodi/addons/plugin.video.jellycon/resources/lib/dir_functions.py", line 247, in process_directory
                                                       url = url.replace('{userid}', user_id)
                                                   TypeError: replace() argument 2 must be str, not None
                                                   -->End of Python script error report<--`

**Screenshots**

**System (please complete the following information):**
 - OS: antiX linux 21
 - Jellyfin Version: unknown (is a friend's server)
 - Kodi Version: 19.1
 - Addon Version: 0.5.7+py3

**Additional context**
Going directly to the "Jellyfin Libraries" folder produces the loading icon but does not go anywhere from there. Restarting Kodi gets a "you haven't connected to this remote server before, would you like to do a speed test?" which also errors out.

**Comment by mcarlton00** [comment]
This looks like you weren't authenticated properly.  Do you have a `/home/NerdTV/.kodi/userdata/addon_data/plugin.video.jellycon/auth.json` file that's populated? (don't share it here, for obvious reasons)

**Comment by taiyoko** [comment]
Yes, but the token and user_id are both listed as "null". If that's because I mis-entered the password (it's a really long password and I was manually typing it due to not installing Discord on that computer to copy/paste from), it might be helpful if somewhere it actually popped an "authentication failed" message instead of just flipping out cryptically.

**Comment by mcarlton00** [comment]
I don't think copy/paste works into Kodi at all actually, but I haven't tried.  But there was an error message added in #220 that hasn't been released yet.

For now, you can delete that file and restart Kodi and it should prompt you to login again.

**Comment by taiyoko** [comment]
Yup, re-authenticating got it working, thanks!
