### ISSUE TITLE
Error connecting to server

### ISSUE THREAD

**Issue by krutburken** [jellyfin/jellycon#236]
**Describe the bug**
App decided to error on me when connecting to a remote server over https and can't seem to get it working. Haven't used this addon in a while so maybe it's just pebcak. Server works fine in other clients (not an url typo, I checked the xml file).

**To Reproduce**
1. Install addon
2. Enter server url when prompted, confirm

**Expected behavior**
Connection successful.

**Logs**
```
2022-10-26 22:09:53.391 T:5681    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellycon/default.py", line 18, in <module>
                                                       main_entry_point()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 23, in wrapper
                                                       value = func(*args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellycon/resources/lib/functions.py", line 148, in main_entry_point
                                                       check_server()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellycon/resources/lib/server_detect.py", line 216, in check_server
                                                       code = quick.get('Code')
                                                   AttributeError: 'str' object has no attribute 'get'
                                                   -->End of Python script error report<--

2022-10-26 22:09:53.571 T:5681     INFO <general>: Python interpreter stopped
2022-10-26 22:09:53.586 T:5680    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.jellycon/?content_type=video
2022-10-26 22:09:53.594 T:5283    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.jellycon/?content_type=video) failed
```

**System (please complete the following information):**
 - OS: Android TV 11
 - Jellyfin Version: 10.8.5
 - Kodi Version: 19.3
 - Addon Version: 0.6.0

**Comment by mcarlton00** [comment]
This is actually already fixed in #235.  Alternatively, if you enable quick connect on the server then it will work now without a new release
