### ISSUE TITLE
UnboundLocalError: local variable 'auth' referenced before assignme

### ISSUE THREAD

**Issue by lsowen** [jellyfin/jellycon#237]
**Describe the bug**
Quick switching of users fails, log of backtrace below

**To Reproduce**
1. Add two users
2. Attempt to switch the user

**Logs**

```
2022-10-29 15:03:21.882 T:453     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.jellycon/?mode=CHANGE_USER) failed
2022-10-29 15:03:57.481 T:781      INFO <general>: initializing python engine.                      
2022-10-29 15:04:05.321 T:781     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnboundLocalError'>
                                                   Error Contents: local variable 'auth' referenced before assignment             
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.jellycon/default.py", line 18, in <module>
                                                       main_entry_point()       
                                                     File "/home/osmc/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 23, in wrapper
                                                       value = func(*args, **kwargs)                                                                                                                                
                                                     File "/home/osmc/.kodi/addons/plugin.video.jellycon/resources/lib/functions.py", line 78, in main_entry_point
                                                       check_server(change_user=True, notify=False)
                                                     File "/home/osmc/.kodi/addons/plugin.video.jellycon/resources/lib/server_detect.py", line 292, in check_server
                                                       if auth:                        
                                                   UnboundLocalError: local variable 'auth' referenced before assignment
                                                   -->End of Python script error report<--  
```

**System (please complete the following information):**
 - OS: osmc (debian 11.5)
 - Jellyfin Version: 10.8.6
 - Kodi Version: 19.4
 - Addon Version: 0.6.0

**Comment by mcarlton00** [comment]
This error _should_ only happen when you cancel the user select dialog.  As long as you go through all the menus it shouldn't be an issue, but it should be fixed to not error regardless
