### ISSUE TITLE
`server_detect.py` throwing an exception on 0.6.0

### ISSUE THREAD

**Issue by cmsimike** [jellyfin/jellycon#242]
**Describe the bug**
Trying to switch users to detect Jellyfin servers on my network I am getting a Kodi error.

**To Reproduce**

1. Go to "add on settings"
2. Click on "change user"
3. If multiple users are already available (as in my case) you see the exception
4. Go to "add on settings"
5. 2. Click on "detect local server"
6. Let the server be found and click on it
7. See the exception

**Expected behavior**

I would like to be able to change user or select the jellyfin instance

**Logs**

```
2022-11-01 18:50:33.742 T:2025340   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/home/mike/.kodi/addons/plugin.video.jellycon/default.py", line 18, in <module>
                                                       main_entry_point()
                                                     File "/home/mike/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 23, in wrapper
                                                       value = func(*args, **kwargs)
                                                     File "/home/mike/.kodi/addons/plugin.video.jellycon/resources/lib/functions.py", line 84, in main_entry_point
                                                       check_server(force=True, change_user=True, notify=False)
                                                     File "/home/mike/.kodi/addons/plugin.video.jellycon/resources/lib/server_detect.py", line 216, in check_server
                                                       code = quick.get('Code')
                                                   AttributeError: 'str' object has no attribute 'get'
                                                   -->End of Python script error report<--
```
```
2022-11-01 18:49:54.082 T:2025327   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/home/mike/.kodi/addons/plugin.video.jellycon/default.py", line 18, in <module>
                                                       main_entry_point()
                                                     File "/home/mike/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 23, in wrapper
                                                       value = func(*args, **kwargs)
                                                     File "/home/mike/.kodi/addons/plugin.video.jellycon/resources/lib/functions.py", line 78, in main_entry_point
                                                       check_server(change_user=True, notify=False)
                                                     File "/home/mike/.kodi/addons/plugin.video.jellycon/resources/lib/server_detect.py", line 216, in check_server
                                                       code = quick.get('Code')
                                                   AttributeError: 'str' object has no attribute 'get'
                                                   -->End of Python script error report<--

```

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Android, Debian, Windows] Ubuntu 22.04
 - Jellyfin Version: [e.g. 10.0.1] 10.8.5
 - Kodi Version: [e.g. 18.3] 19.4
 - Addon Version: [e.g. 0.1.1] .6.0

**Additional context**
Nothing has really (directly) changed on my end. I haven't needed to change the config in a while. This seemed to have started out of no where. Maybe the latest .6.0 update?
Actually this seems confirmed. I used Kodi to install .5.7 and I was able to access "Change user" and "Detect local server" without a problem.

**Comment by mcarlton00** [comment]
Duplicate of #240 and #236, fixed in 0.6.1 released ~1 hour ago

**Comment by cmsimike** [comment]
Sorry I missed it! Thank you.
