### ISSUE TITLE
Cannot connect with quickconnect

### ISSUE THREAD

**Issue by Al3601** [jellyfin/jellycon#245]
**Describe the bug**

As the title say, i cannot login with jellycon addon (Kodi 19.4) , the addon can detect the local server, when i choose it, error notification appear.

"QuickConnect" is enabled on the general settings.

for the server i use https://hub.docker.com/r/linuxserver/jellyfin   with the fillowing

```
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - JELLYFIN_PublishedServerUrl=192.168.0.27
    volumes:
      - /home/pi/videos/library:/config
      - /home/pi/videos/Series:/data/tvshows
      - /home/pi/videos/Films:/data/movies
    ports:
      - 8097:8096
      - 8920:8920 
      - 7359:7359/udp
      - 1900:1900/udp 
    restart: unless-stopped
```

Note : i already have emby server on another NAS who using the 8096 with embycon using quickconnect with no problem.

is there anyway to tell the addon im using the 8097 port ? 
When i use http://192.168.0.27/QuickConnect/Initiate    i get 404 error
When i use http://192.168.0.27:8097/QuickConnect/Initiate    i get "Error processing request." but it is working here.

**System :**
 - OS: Linux
 - Jellyfin Version:  10.8.7
 - Kodi Version: 19.4
 - Addon Version: 0.6.1

**Expected behavior**
to output a pin code on the server UI

**Logs**

```
2022-11-11 19:42:35.587 T:3621    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.MissingSchema'>
                                                   Error Contents: Invalid URL '192.168.0.27/QuickConnect/Initiate': No scheme supplied. Perhaps you meant http://192.168.0.27/QuickConnect/Initiate?
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.jellycon/default.py", line 18, in <module>
                                                       main_entry_point()
                                                     File "/home/osmc/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 23, in wrapper
                                                       value = func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.jellycon/resources/lib/functions.py", line 148, in main_entry_point
                                                       check_server()
                                                     File "/home/osmc/.kodi/addons/plugin.video.jellycon/resources/lib/server_detect.py", line 218, in check_server
                                                       quick = api.get('/QuickConnect/Initiate')
                                                     File "/home/osmc/.kodi/addons/plugin.video.jellycon/resources/lib/jellyfin.py", line 38, in get
                                                       r = requests.get(url, headers=self.headers, verify=self.verify_cert)
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
                                                       return request('get', url, params=params, **kwargs)
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/api.py", line 61, in request
                                                       return session.request(method=method, url=url, **kwargs)
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 515, in request
                                                       prep = self.prepare_request(req)
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 443, in prepare_request
                                                       p.prepare(
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/models.py", line 318, in prepare
                                                       self.prepare_url(url, params)
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/models.py", line 392, in prepare_url
                                                       raise MissingSchema(error)
                                                   requests.exceptions.MissingSchema: Invalid URL '192.168.0.27/QuickConnect/Initiate': No scheme supplied. Perhaps you meant http://192.168.0.27/QuickConnect/Initiate?
                                                   -->End of Python script error report<--
```

**Comment by mcarlton00** [comment]
> - JELLYFIN_PublishedServerUrl=192.168.0.27

I believe this is the problem.  This variable is meant to be a full URL, so the current value is missing both the schema and port number.  If you were to change this value to `http://192.168.0.27:8097` and restart the container, it should start working correctly.

**Comment by mcarlton00** [comment]
Closing as it's not a client side bug.  We simply use what the server provides, it has to be configured properly to work
