### ISSUE TITLE
Error when loading remote Jellyfin library

### ISSUE THREAD

**Issue by zhorvath83** [jellyfin/jellycon#264]
**Describe the bug**
Attempting to load remote Jellyfin library gives a generic "see logs" error.

**To Reproduce**
1. Adding a server to Jellycon and signing in
2. Go to Addons
3. Go to JellyCon
4. Go to Jellyfin Libraries

**Expected behavior**
Libraries defined in Jellyfin should came up.

**Logs**
`
2023-01-16 20:14:54.301 T:978      INFO <general>: initializing python engine.
2023-01-16 20:14:55.041 T:978      INFO <general>: CPythonInvoker(1, /home/zhorvath83/.kodi/addons/plugin.video.jellycon/default.py): script successfully run
2023-01-16 20:14:55.152 T:978      INFO <general>: Python interpreter stopped
2023-01-16 20:14:59.710 T:982      INFO <general>: initializing python engine.
2023-01-16 20:15:00.233 T:982     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: PyCapsule_Import "charset_normalizer.md__mypyc.init_charset_normalizer___md" is not valid
                                                   Traceback (most recent call last):
                                                     File "/home/zhorvath83/.kodi/addons/plugin.video.jellycon/default.py", line 6, in <module>
                                                       from resources.lib.functions import main_entry_point
                                                     File "/home/zhorvath83/.kodi/addons/plugin.video.jellycon/resources/lib/functions.py", line 17, in <module>
                                                       from .jellyfin import api
                                                     File "/home/zhorvath83/.kodi/addons/plugin.video.jellycon/resources/lib/jellyfin.py", line 6, in <module>
                                                       import requests
                                                     File "/home/zhorvath83/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 48, in <module>
                                                       from charset_normalizer import __version__ as charset_normalizer_version
                                                     File "/usr/local/lib/python3.9/dist-packages/charset_normalizer/__init__.py", line 24, in <module>
                                                       from .api import from_bytes, from_fp, from_path
                                                     File "/usr/local/lib/python3.9/dist-packages/charset_normalizer/api.py", line 5, in <module>
                                                       from .cd import (
                                                     File "/usr/local/lib/python3.9/dist-packages/charset_normalizer/cd.py", line 9, in <module>
                                                       from .md import is_suspiciously_successive_range
                                                   AttributeError: PyCapsule_Import "charset_normalizer.md__mypyc.init_charset_normalizer___md" is not valid
                                                   -->End of Python script error report<--
`

**Screenshots**

**System (please complete the following information):**
 - OS: Raspberry Pi OS Lite 64-bit (Debian version: 11)
 - Jellyfin Version: 10.8.8
 - Kodi Version: 19.4.0 Git:20221007-166303c4f0
 - Addon Version: 0.6.1+py3

**Additional context**
Tried to start over by deleting the whole .kodi dir from user's home and re-adding and re-authenticating to Jellyfin. Everything went well till opening Jellyfin Libraries (in Jellycon).

**Comment by mcarlton00** [comment]
This looks like either you're missing a dependency or something on your OS isn't correct.  That's failing deep in the dependency tree and not in code that I can have any effect on.

for example, `File "/usr/local/lib/python3.9/dist-packages/charset_normalizer/cd.py`.  This is a OS level package, not a Kodi python addon.

**Comment by zhorvath83** [comment]
Thanks for your help, after re-flashing the Raspi OS and installing only Kodi and Jellycon, everything went well, no problem at all.
