### ISSUE TITLE
Cannot validate trusted SSL certificate

### ISSUE THREAD

**Issue by rockerbacon** [jellyfin/jellycon#278]
**Describe the bug**

I use my own CA which I have configured in all devices connected in a Wireguard VPN. This allows me to sign my own certificates without running into the self-signed certificate annoyances most people are familiar with.
Every now and then I sadly run into software which cannot properly use the OS trust store and will fail to validate the certificates. Jellycon seems to be one such software.

**To Reproduce**

1. Create a private key and certificate for your own CA
2. Create and sign a certificate for Jellyfin using your CA
3. Configure Jellyfin to use the created certificate (I'm using a reverse proxy)
4. Add the CA certificate from step 1 to the trusted store of the clients you want to connect to Jellyfin
5. Test that the client can properly validate the certificate:
    - Easiest way is to open a browser and check that it can access the Jellyfin web interface with HTTPS without any warnings;
    - If you're on a linux distro which uses openssl you can also use the command: `openssl s_client -connect your.jellyfin.domain.com:443 </dev/null | openssl verify`
 6. Open Kodi on the client
 7. Try to connect to your Jellyfin server using HTTPS

**Expected behavior**

Jellycon should be able to validate certificates from all CAs in the system's trusted store.

**Logs**

```
2023-03-13 20:47:44.155 T:9616    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.SSLError'>
                                                   Error Contents: HTTPSConnectionPool(host='stream.lab309.com.br', port=443): Max retries exceeded with url: /QuickConnect/Initiate (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))
                                                   Traceback (most recent call last):
                                                     File "/home/vitor.santos//.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 703, in urlopen
                                                       httplib_response = self._make_request(
                                                                          ^^^^^^^^^^^^^^^^^^^
                                                     File "/home/vitor.santos//.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 386, in _make_request
                                                       self._validate_conn(conn)
                                                     File "/home/vitor.santos//.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 1042, in _validate_conn
                                                       conn.connect()
                                                     File "/home/vitor.santos//.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 414, in connect
                                                       self.sock = ssl_wrap_socket(
                                                                   ^^^^^^^^^^^^^^^^
                                                     File "/home/vitor.santos//.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
                                                       ssl_sock = _ssl_wrap_socket_impl(
                                                                  ^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/vitor.santos//.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
                                                       return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib64/python3.11/ssl.py", line 517, in wrap_socket
                                                       return self.sslsocket_class._create(
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib64/python3.11/ssl.py", line 1075, in _create
                                                       self.do_handshake()
                                                     File "/usr/lib64/python3.11/ssl.py", line 1346, in do_handshake
                                                       self._sslobj.do_handshake()
                                                   ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/vitor.santos//.kodi/addons/script.module.requests/lib/requests/adapters.py", line 440, in send
                                                       resp = conn.urlopen(
                                                              ^^^^^^^^^^^^^
                                                     File "/home/vitor.santos//.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 787, in urlopen
                                                       retries = retries.increment(
                                                                 ^^^^^^^^^^^^^^^^^^
                                                     File "/home/vitor.santos//.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 592, in increment
                                                       raise MaxRetryError(_pool, url, error or ResponseError(cause))
                                                   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='stream.lab309.com.br', port=443): Max retries exceeded with url: /QuickConnect/Initiate (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/vitor.santos//.kodi/addons/plugin.video.jellycon/service.py", line 52, in <module>
                                                       check_server()
                                                     File "/home/vitor.santos//.kodi/addons/plugin.video.jellycon/resources/lib/server_detect.py", line 221, in check_server
                                                       quick = api.get('/QuickConnect/Initiate')
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/vitor.santos//.kodi/addons/plugin.video.jellycon/resources/lib/jellyfin.py", line 40, in get
                                                       r = requests.get(url, headers=self.headers, verify=self.verify_cert)
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/vitor.santos//.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
                                                       return request('get', url, params=params, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/vitor.santos//.kodi/addons/script.module.requests/lib/requests/api.py", line 61, in request
                                                       return session.request(method=method, url=url, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/vitor.santos//.kodi/addons/script.module.requests/lib/requests/sessions.py", line 529, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/vitor.santos//.kodi/addons/script.module.requests/lib/requests/sessions.py", line 645, in send
                                                       r = adapter.send(request, **kwargs)
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/vitor.santos//.kodi/addons/script.module.requests/lib/requests/adapters.py", line 517, in send
                                                       raise SSLError(e, request=request)
                                                   requests.exceptions.SSLError: HTTPSConnectionPool(host='stream.lab309.com.br', port=443): Max retries exceeded with url: /QuickConnect/Initiate (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))
                                                   -->End of Python script error report<--
```

**System (please complete the following information):**
 - OS: Fedora 37 (both client and server)
 - Jellyfin Version: 10.8.9
 - Kodi Version: 19.5, installed from RPM Fusion - free
 - Addon Version: 0.7.0+py3

**Comment by mcarlton00** [comment]
This really isn't up to us.  Python uses certificates provided by the certifi package, not the OS certificate store.

https://requests.readthedocs.io/en/latest/user/advanced/#ca-certificates

**Comment by Kline-** [comment]
@rockerbacon You can workaround this by disabling sslverify in the Jellyfin settings.xml file on the device running Kodi. I had to do this on my ShieldTV even after adding my custom CA to Kodi by overriding the default cacerts file.
