### ISSUE TITLE
Watched status not updating from Kodi

### ISSUE THREAD

**Issue by ColonelPanic-42** [jellyfin/jellycon#304]
**Describe the bug**
Just installed today (migrated from Emby), for some reason the watched state won't update from Kodi whether from finishing a video or manually marking a file as watched/unwatched. The watched state can be updated from Jellyfin's web UI without issue and this reflects back to Kodi, but the status can't be updated from Kodi back to Jellyfin.

**To Reproduce**

1. Watch any video to completion, OR manually set the watched state of a file

**Expected behavior**

The watched state of the file is updated in Kodi. The watched state is persisted in Jellyfin and is reflected in the web UI.

**Logs**
Log snippets taken when triggering "Mark as watched" in Kodi:
From `kodi.log`
```
2023-11-19 19:58:34.430 T:32246    info <general>: JELLYFIN.default -> DEBUG::default.py:16 About to enter mainEntryPoint()
2023-11-19 19:58:34.431 T:32246    info <general>: JELLYFIN.resources.lib.functions -> DEBUG::resources/lib/functions.py:57 ===== JellyCon START =====
2023-11-19 19:58:34.435 T:32246    info <general>: JELLYFIN.resources.lib.functions -> DEBUG::resources/lib/functions.py:68 Running Python: sys.version_info(major=3, minor=11, micro=2, releaselevel='final', serial=0)
2023-11-19 19:58:34.436 T:32246    info <general>: JELLYFIN.resources.lib.functions -> DEBUG::resources/lib/functions.py:69 Running JellyCon: 0.7.0+py3
2023-11-19 19:58:34.436 T:32246    info <general>: JELLYFIN.resources.lib.functions -> DEBUG::resources/lib/functions.py:70 Kodi BuildVersion: 20.2 (20.2.0) Git:20.2-Nexus
2023-11-19 19:58:34.437 T:32246    info <general>: JELLYFIN.resources.lib.functions -> DEBUG::resources/lib/functions.py:73 Kodi Version: 20
2023-11-19 19:58:34.437 T:32246    info <general>: JELLYFIN.resources.lib.functions -> DEBUG::resources/lib/functions.py:74 Script argument data: ['plugin://plugin.video.jellycon/', '578', '?media_type=Season&mode=GET_CONTENT&url=%2fShows%2f07b06ab126554ff7e03b74f49c24cf5a%2fEpisodes%3fuserId%3d%7buserid%7d%26seasonId%3d949fb4a39113be28598c923992ae357e%26IsVirtualUnAired%3dfalse%26IsMissing%3dfalse%26Fields%3dSpecialEpisodeNumbers%2cDateCreated%2cEpisodeCount%2cSeasonCount%2cPath%2cGenres%2cStudios%2cEtag%2cTaglines%2cSortName%2cRecursiveItemCount%2cChildCount%2cProductionLocations%2cCriticRating%2cOfficialRating%2cCommunityRating%2cPremiereDate%2cProductionYear%2cAirTime%2cStatus%2cTags%2cMediaStreams%2cOverview%26format%3djson', 'resume:false']
2023-11-19 19:58:34.437 T:32246    info <general>: JELLYFIN.resources.lib.functions -> DEBUG::resources/lib/functions.py:310 Parameter string: ?media_type=Season&mode=GET_CONTENT&url=%2fShows%2f07b06ab126554ff7e03b74f49c24cf5a%2fEpisodes%3fuserId%3d%7buserid%7d%26seasonId%3d949fb4a39113be28598c923992ae357e%26IsVirtualUnAired%3dfalse%26IsMissing%3dfalse%26Fields%3dSpecialEpisodeNumbers%2cDateCreated%2cEpisodeCount%2cSeasonCount%2cPath%2cGenres%2cStudios%2cEtag%2cTaglines%2cSortName%2cRecursiveItemCount%2cChildCount%2cProductionLocations%2cCriticRating%2cOfficialRating%2cCommunityRating%2cPremiereDate%2cProductionYear%2cAirTime%2cStatus%2cTags%2cMediaStreams%2cOverview%26format%3djson
2023-11-19 19:58:34.437 T:32246    info <general>: JELLYFIN.resources.lib.functions -> DEBUG::resources/lib/functions.py:311 Plugin Path string: plugin://plugin.video.jellycon/
2023-11-19 19:58:34.439 T:32246    info <general>: JELLYFIN.resources.lib.functions -> DEBUG::resources/lib/functions.py:319 JellyCon -> Detected parameters: {'media_type': 'Season', 'mode': 'GET_CONTENT', 'url': '/Shows/07b06ab126554ff7e03b74f49c24cf5a/Episodes?userId={userid}&seasonId=949fb4a39113be28598c923992ae357e&IsVirtualUnAired=false&IsMissing=false&Fields=SpecialEpisodeNumbers,DateCreated,EpisodeCount,SeasonCount,Path,Genres,Studios,Etag,Taglines,SortName,RecursiveItemCount,ChildCount,ProductionLocations,CriticRating,OfficialRating,CommunityRating,PremiereDate,ProductionYear,AirTime,Status,Tags,MediaStreams,Overview&format=json', 'request_path': '/'}
2023-11-19 19:58:34.439 T:32246    info <general>: JELLYFIN.resources.lib.functions -> DEBUG::resources/lib/functions.py:77 Script params: {'media_type': 'Season', 'mode': 'GET_CONTENT', 'url': '/Shows/07b06ab126554ff7e03b74f49c24cf5a/Episodes?userId={userid}&seasonId=949fb4a39113be28598c923992ae357e&IsVirtualUnAired=false&IsMissing=false&Fields=SpecialEpisodeNumbers,DateCreated,EpisodeCount,SeasonCount,Path,Genres,Studios,Etag,Taglines,SortName,RecursiveItemCount,ChildCount,ProductionLocations,CriticRating,OfficialRating,CommunityRating,PremiereDate,ProductionYear,AirTime,Status,Tags,MediaStreams,Overview&format=json', 'request_path': '/'}
2023-11-19 19:58:34.439 T:32246    info <general>: JELLYFIN.resources.lib.functions -> DEBUG::resources/lib/functions.py:150 JellyCon -> Mode: GET_CONTENT
2023-11-19 19:58:34.440 T:32246    info <general>: JELLYFIN.resources.lib.functions -> DEBUG::resources/lib/functions.py:151 JellyCon -> URL: /Shows/07b06ab126554ff7e03b74f49c24cf5a/Episodes?userId={userid}&seasonId=949fb4a39113be28598c923992ae357e&IsVirtualUnAired=false&IsMissing=false&Fields=SpecialEpisodeNumbers,DateCreated,EpisodeCount,SeasonCount,Path,Genres,Studios,Etag,Taglines,SortName,RecursiveItemCount,ChildCount,ProductionLocations,CriticRating,OfficialRating,CommunityRating,PremiereDate,ProductionYear,AirTime,Status,Tags,MediaStreams,Overview&format=json
2023-11-19 19:58:34.440 T:32246    info <general>: JELLYFIN.resources.lib.dir_functions -> DEBUG::resources/lib/dir_functions.py:27 == ENTER: getContent ==
2023-11-19 19:58:34.440 T:32246    info <general>: JELLYFIN.resources.lib.dir_functions -> DEBUG::resources/lib/dir_functions.py:34 URL: /Shows/07b06ab126554ff7e03b74f49c24cf5a/Episodes?userId={userid}&seasonId=949fb4a39113be28598c923992ae357e&IsVirtualUnAired=false&IsMissing=false&Fields=SpecialEpisodeNumbers,DateCreated,EpisodeCount,SeasonCount,Path,Genres,Studios,Etag,Taglines,SortName,RecursiveItemCount,ChildCount,ProductionLocations,CriticRating,OfficialRating,CommunityRating,PremiereDate,ProductionYear,AirTime,Status,Tags,MediaStreams,Overview&format=json
2023-11-19 19:58:34.440 T:32246    info <general>: JELLYFIN.resources.lib.dir_functions -> DEBUG::resources/lib/dir_functions.py:35 MediaType: Season
2023-11-19 19:58:34.441 T:32246    info <general>: JELLYFIN.resources.lib.dir_functions -> DEBUG::resources/lib/dir_functions.py:81 media_type:season content_type:episodes view_type:Episodes 
2023-11-19 19:58:34.445 T:32246    info <general>: JELLYFIN.resources.lib.dir_functions -> DEBUG::resources/lib/dir_functions.py:225 == ENTER: processDirectory ==
2023-11-19 19:58:34.585 T:32246    info <general>: JELLYFIN.resources.lib.datamanager -> DEBUG::resources/lib/datamanager.py:54 last_content_url : use_cache=True url=/Shows/07b06ab126554ff7e03b74f49c24cf5a/Episodes?userId=32a1f5b020ef4c3789e0d0ecf45e94ca&seasonId=949fb4a39113be28598c923992ae357e&IsVirtualUnAired=false&IsMissing=false&Fields=SpecialEpisodeNumbers,DateCreated,EpisodeCount,SeasonCount,Path,Genres,Studios,Etag,Taglines,SortName,RecursiveItemCount,ChildCount,ProductionLocations,CriticRating,OfficialRating,CommunityRating,PremiereDate,ProductionYear,AirTime,Status,Tags,MediaStreams,Overview&format=json
2023-11-19 19:58:34.586 T:32246    info <general>: JELLYFIN.resources.lib.datamanager -> DEBUG::resources/lib/datamanager.py:81 Loading url data from cached pickle data
2023-11-19 19:58:34.618 T:32246 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-11-19 19:58:34.618 T:32246 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-11-19 19:58:34.621 T:32246    info <general>: Skipped 42 duplicate messages..
2023-11-19 19:58:34.621 T:32246 warning <general>: ListItem.setRating() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setRating().
2023-11-19 19:58:34.621 T:32246 warning <general>: "resumetime" in ListItem.setProperty() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setResumePoint().
2023-11-19 19:58:34.621 T:32246 warning <general>: "totaltime" in ListItem.setProperty() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setResumePoint().
2023-11-19 19:58:34.622 T:32246 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-11-19 19:58:34.622 T:32246 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-11-19 19:58:34.622 T:32246    info <general>: Skipped 2 duplicate messages..
2023-11-19 19:58:34.622 T:32246 warning <general>: ListItem.setRating() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setRating().
2023-11-19 19:58:34.622 T:32246 warning <general>: "resumetime" in ListItem.setProperty() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setResumePoint().
2023-11-19 19:58:34.622 T:32246 warning <general>: "totaltime" in ListItem.setProperty() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setResumePoint().
2023-11-19 19:58:34.622 T:32246 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-11-19 19:58:34.622 T:32246 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-11-19 19:58:34.622 T:32246    info <general>: Skipped 2 duplicate messages..
2023-11-19 19:58:34.622 T:32246 warning <general>: ListItem.setRating() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setRating().
2023-11-19 19:58:34.623 T:32246 warning <general>: "resumetime" in ListItem.setProperty() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setResumePoint().
2023-11-19 19:58:34.623 T:32246 warning <general>: "totaltime" in ListItem.setProperty() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setResumePoint().
2023-11-19 19:58:34.623 T:32246 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-11-19 19:58:34.623 T:32246 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-11-19 19:58:34.623 T:32246    info <general>: Skipped 2 duplicate messages..
2023-11-19 19:58:34.623 T:32246 warning <general>: ListItem.setRating() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setRating().
2023-11-19 19:58:34.623 T:32246 warning <general>: "resumetime" in ListItem.setProperty() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setResumePoint().
2023-11-19 19:58:34.623 T:32246 warning <general>: "totaltime" in ListItem.setProperty() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setResumePoint().
2023-11-19 19:58:34.623 T:32246 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-11-19 19:58:34.623 T:32246 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-11-19 19:58:34.623 T:32246    info <general>: Skipped 3 duplicate messages..
2023-11-19 19:58:34.623 T:32246 warning <general>: ListItem.setRating() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setRating().
2023-11-19 19:58:34.624 T:32246 warning <general>: "resumetime" in ListItem.setProperty() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setResumePoint().
2023-11-19 19:58:34.624 T:32246 warning <general>: "totaltime" in ListItem.setProperty() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setResumePoint().
2023-11-19 19:58:34.624 T:32246 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-11-19 19:58:34.624 T:32246 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-11-19 19:58:34.624 T:32246    info <general>: Skipped 2 duplicate messages..
2023-11-19 19:58:34.624 T:32246 warning <general>: ListItem.setRating() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setRating().
2023-11-19 19:58:34.624 T:32246 warning <general>: "resumetime" in ListItem.setProperty() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setResumePoint().
2023-11-19 19:58:34.624 T:32246 warning <general>: "totaltime" in ListItem.setProperty() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setResumePoint().
2023-11-19 19:58:34.624 T:32246 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-11-19 19:58:34.624 T:32246 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-11-19 19:58:34.624 T:32246    info <general>: Skipped 3 duplicate messages..
2023-11-19 19:58:34.624 T:32246 warning <general>: ListItem.setRating() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setRating().
2023-11-19 19:58:34.624 T:32246 warning <general>: "resumetime" in ListItem.setProperty() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setResumePoint().
2023-11-19 19:58:34.625 T:32246 warning <general>: "totaltime" in ListItem.setProperty() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setResumePoint().
2023-11-19 19:58:34.625 T:32246 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-11-19 19:58:34.625 T:32246 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-11-19 19:58:34.628 T:32246    info <general>: Skipped 44 duplicate messages..
2023-11-19 19:58:34.628 T:32246 warning <general>: ListItem.setRating() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setRating().
2023-11-19 19:58:34.628 T:32246 warning <general>: "resumetime" in ListItem.setProperty() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setResumePoint().
2023-11-19 19:58:34.628 T:32246 warning <general>: "totaltime" in ListItem.setProperty() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setResumePoint().
2023-11-19 19:58:34.629 T:32247    info <general>: JELLYFIN.resources.lib.datamanager -> DEBUG::resources/lib/datamanager.py:164 CacheManagerThread : Started
2023-11-19 19:58:34.629 T:32246    info <general>: JELLYFIN.resources.lib.dir_functions -> DEBUG::resources/lib/dir_functions.py:121 total_records: 0
2023-11-19 19:58:34.630 T:32246    info <general>: JELLYFIN.resources.lib.dir_functions -> DEBUG::resources/lib/dir_functions.py:183 SETTING_SORT for media type: Episodes
2023-11-19 19:58:34.634 T:32246    info <general>: JELLYFIN.resources.lib.dir_functions -> DEBUG::resources/lib/dir_functions.py:200 SETTING_SORT preset_sort_order: 0
2023-11-19 19:58:34.635 T:32246    info <general>: JELLYFIN.resources.lib.dir_functions -> DEBUG::resources/lib/dir_functions.py:173 No view id for view type:view-episodes
2023-11-19 19:58:34.636 T:32246    info <general>: JELLYFIN.resources.lib.functions -> DEBUG::resources/lib/functions.py:178 ===== JellyCon FINISHED =====
2023-11-19 19:58:34.636 T:32246    info <general>: CPythonInvoker(714, /storage/.kodi/addons/plugin.video.jellycon/default.py): waiting on thread 2615202432
2023-11-19 19:58:34.670 T:32247    info <general>: JELLYFIN.resources.lib.datamanager -> DEBUG::resources/lib/datamanager.py:191 CacheManagerThread : Reloading to recheck data hashes
2023-11-19 19:58:34.670 T:32247    info <general>: JELLYFIN.resources.lib.datamanager -> DEBUG::resources/lib/datamanager.py:193 CacheManagerThread : Cache Hash : b45f273ea5abae4f4834ed9a6eeb808e
2023-11-19 19:58:34.727 T:32247    info <general>: JELLYFIN.resources.lib.datamanager -> DEBUG::resources/lib/datamanager.py:219 CacheManagerThread : Loaded Hash : b45f273ea5abae4f4834ed9a6eeb808e
2023-11-19 19:58:34.731 T:32247    info <general>: JELLYFIN.resources.lib.datamanager -> DEBUG::resources/lib/datamanager.py:249 CacheManagerThread : Updating last used date for cache data
2023-11-19 19:58:34.731 T:32247    info <general>: JELLYFIN.resources.lib.datamanager -> DEBUG::resources/lib/datamanager.py:251 CacheManagerThread : Exited
```
From Jellyfin log
```
[2023-11-19 09:56:20.133 +00:00] [DBG] [30] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2023-11-19 09:56:20.133 +00:00] [DBG] [30] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2023-11-19 09:56:20.133 +00:00] [DBG] [30] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: EpisodeCount is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'EpisodeCount' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter)
[2023-11-19 09:56:20.133 +00:00] [DBG] [30] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: SeasonCount is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'SeasonCount' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter)
[2023-11-19 09:56:20.133 +00:00] [DBG] [30] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: CriticRating is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'CriticRating' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter)
[2023-11-19 09:56:20.133 +00:00] [DBG] [30] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: OfficialRating is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'OfficialRating' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter)
[2023-11-19 09:56:20.134 +00:00] [DBG] [30] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: CommunityRating is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'CommunityRating' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter)
[2023-11-19 09:56:20.134 +00:00] [DBG] [30] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: PremiereDate is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'PremiereDate' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter)
[2023-11-19 09:56:20.134 +00:00] [DBG] [30] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: ProductionYear is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'ProductionYear' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter)
[2023-11-19 09:56:20.134 +00:00] [DBG] [30] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: Status is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'Status' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter)
[2023-11-19 09:56:20.898 +00:00] [DBG] [28] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2023-11-19 09:56:20.898 +00:00] [DBG] [28] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
```

**System (please complete the following information):**
 - OS: Ubuntu 23.04
 - Jellyfin Version: 10.8.12 (Docker)
 - Kodi Version: 20.2

**Comment by ColonelPanic-42** [comment]
Neermind :roll_eyes: apparently all it needed was a reboot of Kodi to start working. Strange for a plugin to not work correctly until after a reboot but still
