### ISSUE TITLE
JellyCon doesn't connect anymore with "Invalid URL '192.168.1.1/QuickConnect/Initiate': No scheme supplied"

### ISSUE THREAD

**Issue by szotsaki** [jellyfin/jellycon#335]
**Describe the bug**

In the error log the following message appears:

```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'requests.exceptions.MissingSchema'>
Error Contents: Invalid URL '192.168.1.1/QuickConnect/Initiate': No scheme supplied. Perhaps you meant https://192.168.1.1/QuickConnect/Initiate?
Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellycon/default.py", line 18, in <module>
    main_entry_point()
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 25, in wrapper
    value = func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellycon/resources/lib/functions.py", line 158, in main_entry_point
    check_server()
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellycon/resources/lib/server_detect.py", line 221, in check_server
    quick = api.get('/QuickConnect/Initiate')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellycon/resources/lib/jellyfin.py", line 40, in get
    r = requests.get(url, headers=self.headers, verify=self.verify_cert)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '192.168.1.1/QuickConnect/Initiate': No scheme supplied. Perhaps you meant https://192.168.1.1/QuickConnect/Initiate?
-->End of Python script error report<--
```

**To Reproduce**

I don't know when it got broken. 

I was in Jellyfin's settings screen some hours before (without modifying anything) and I exited from the menu with the OK button.

I've just checked and the server URL contains the "http" schema there.

**Expected behavior**

* JellyCon doesn't remove the schema from the connection URL
* JellyCon has clear error message saying that it could not connect to the Jellyfin server.

**System (please complete the following information):**
 - OS: Shield
 - Jellyfin Version: 10.9.2
 - Kodi Version: 21.0
 - Addon Version: 0.8.0

**Comment by szotsaki** [comment]
It's reproducible. It happens when you either newly install the extension or start a server discovery. It plugin successfully finds the server but fails to correctly fill out the information.

Instead of `http://192.168.1.1:8096` Jellycon writes `192.168.1.1` only.

**Comment by mcarlton00** [comment]
This means you have your autodiscovery URL in the server configured wrong.  It needs to have a scheme and port attached to it
