### ISSUE TITLE
Kodi Matrix - Jellycon Error when opening "Next Episodes

### ISSUE THREAD

**Issue by quixventure** [jellyfin/jellycon#64]
**Describe the bug**
With a fresh install of Kodi Matrix and JellyCon from the Jel;lyfin repository, most views do not work. 

All Shows under a library are fine. but any of the Recent, Next, In Progress, etc generate an error.

**To Reproduce**

Go to JellyCon Addon
Select a Library or Global Library
Select "Next Up"

**Expected behaviour**
Return of net up episodes

**Logs**

2021-04-15 15:47:02.671 T:3269     INFO <general>: Python interpreter stopped
2021-04-15 15:47:05.590 T:3272     INFO <general>: initializing python engine.
2021-04-15 15:47:05.782 T:3272  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-04-15 15:47:06.777 T:3272    ERROR <general>: Skipped 5 duplicate messages..
2021-04-15 15:47:06.777 T:3272    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'NameError'>
                                                   Error Contents: name 'unicode' is not defined
                                                   Traceback (most recent call last):
                                                     File "/home/mark/.kodi/addons/plugin.video.jellycon/default.py", line 18, in <module>
                                                       main_entry_point()
                                                     File "/home/mark/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 23, in wrapper
                                                       value = func(*args, **kwargs)
                                                     File "/home/mark/.kodi/addons/plugin.video.jellycon/resources/lib/functions.py", line 157, in main_entry_point
                                                       get_content(param_url, params)
                                                     File "/home/mark/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 23, in wrapper
                                                       value = func(*args, **kwargs)
                                                     File "/home/mark/.kodi/addons/plugin.video.jellycon/resources/lib/dir_functions.py", line 118, in get_content
                                                       dir_items, detected_type, total_records = process_directory(url, progress, params, use_cache)
                                                     File "/home/mark/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 23, in wrapper
                                                       value = func(*args, **kwargs)
                                                     File "/home/mark/.kodi/addons/plugin.video.jellycon/resources/lib/dir_functions.py", line 251, in process_directory
                                                       cache_file, item_list, total_records, cache_thread = data_manager.get_items(url, gui_options, use_cache)
                                                     File "/home/mark/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 23, in wrapper
                                                       value = func(*args, **kwargs)
                                                     File "/home/mark/.kodi/addons/plugin.video.jellycon/resources/lib/datamanager.py", line 123, in get_items
                                                       item_data = extract_item_info(item, gui_options)
                                                     File "/home/mark/.kodi/addons/plugin.video.jellycon/resources/lib/item_functions.py", line 181, in extract_item_info
                                                       item_details.name = unicode(name_format).format(**name_info).strip()
                                                   NameError: name 'unicode' is not defined
                                                   -->End of Python script error report<--
                                                   
2021-04-15 15:47:06.938 T:3272     INFO <general>: Python interpreter stopped
2021-04-15 15:47:06.945 T:3271    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.jellycon/?media_type=Episodes&mode=GET_CONTENT&name_format=Episode%7cepisode_name_format&sort=none&url=%7bserver%7d%2fUsers%2f%7buserid%7d%2fItems%3fParentId%3d117c458a200a6c44e841b872eba96cad%26Fields%3d%7bfield_filters%7d%26ImageTypeLimit%3d1%26IsMissing%3dFalse%26IncludeItemTypes%3dEpisode%26Recursive%3dTrue%26format%3djson%26Limit%3d%7bItemLimit%7d%26SortBy%3dDateCreated%26SortOrder%3dDescending%26Filters%3dIsNotFolder
2021-04-15 15:47:06.964 T:2913    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.jellycon/?media_type=Episodes&mode=GET_CONTENT&name_format=Episode%7cepisode_name_format&sort=none&url=%7bserver%7d%2fUsers%2f%7buserid%7d%2fItems%3fParentId%3d117c458a200a6c44e841b872eba96cad%26Fields%3d%7bfield_filters%7d%26ImageTypeLimit%3d1%26IsMissing%3dFalse%26IncludeItemTypes%3dEpisode%26Recursive%3dTrue%26format%3djson%26Limit%3d%7bItemLimit%7d%26SortBy%3dDateCreated%26SortOrder%3dDescending%26Filters%3dIsNotFolder) failed
2021-04-15 15:47:09.564 T:2913     INFO <general>: GL: Maximum texture width: 16384
2021-04-15 15:47:09.938 T:2913     INFO <general>: GL: Enabling VSYNC

**Screenshots**

**System (please complete the following information):**
 - OS: Arch Linux, Windows 10
 - Jellyfin Version:  10.7.2
 - Kodi Version: 19.0
 - Addon Version: 0.4.2+py3

**Additional context**
Playback is fine if you go to all shows in a library and drill down, just filtered lists have an issue.

**Comment by mcarlton00** [comment]
Should be fixed by #62
